# Generated by Django 4.2.5 on 2023-12-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='scam',
            name='category',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scam',
            name='domain',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
