# Generated by Django 4.2.5 on 2023-12-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_scammodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='scammodel',
            name='status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
